export enum RedisKeys {
  USER_INTRO_MESSAGE_ID_ALERTS = 'USER:$user$:INTRO_MESSAGE_ID:ALERTS',
  USER_INTRO_MESSAGE_ID_POSITIONS = 'USER:$user$:INTRO_MESSAGE_ID:POSITIONS',
  USER_OKX_SECRETS = 'USER:$user$:OKX_SECRETS',
  USER_PRICE_ALERT = 'PRICE_ALERT:$user$:$instrument$:$price$',
  USER_POSITION = 'POSITION:$user$:$position$'
}

export enum RedisIndexes {
  PRICE_ALERTS = 'INDEX:PRICE_ALERTS',
  POSITIONS = 'INDEX:POSITIONS'
}
